name: My Githun Actions Workflow
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  testing_github:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        run: echo "Hello, Github Actions"
      - name: Display repo name
        run: echo "This workflow is triggered from ${{ github.repository }}"